export const SITE_CONFIG = {
  name: "Chiromo Tech Club",
  shortName: "CTC",
  tagline: "Building Africa's Next Generation of Innovators.",
  description:
    "Chiromo Tech Club (CTC) is a student-led technology community at the University of Nairobi Chiromo Campus — AI, software engineering, cloud, cybersecurity, robotics, data science, and design.",
  url: "https://chiromo-tech-club.vercel.app",
  locale: "en_KE",
  keywords: [
    "Chiromo Tech Club",
    "CTC",
    "Chiromo",
    "tech club",
    "University of Nairobi",
    "UoN",
    "UoN Chiromo",
    "Chiromo Campus",
    "student tech club Kenya",
    "Nairobi tech community",
    "AI club Kenya",
    "software engineering club",
    "cybersecurity club UoN",
    "robotics Chiromo",
    "data science club Nairobi",
    "join Chiromo Tech Club",
  ],
  socials: {
    github: "https://github.com/chiromo-tech-club",
    instagram: "https://instagram.com/chiromotechclub",
    linkedin: "https://linkedin.com/company/chiromo-tech-club",
  },
} as const;
